version: '3'

services:
  backend-java:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    command: ["java", "-jar", "/app/backend-java.jar"]
    stdin_open: true
    tty: true
    depends_on:
      - meuDB
    environment:
      - DATABASE_HOST=meuDB
      - DATABASE_PORT=3306
      - DATABASE_USER=meuDB
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=meuDB
    ports:
      - "8080:8080"
    networks:
      app_net:
        ipv4_address: 172.20.0.2

  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      app_net:
        ipv4_address: 172.20.0.4

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: meuDB
      MYSQL_USER: meuDB
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 172.20.0.3
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
