version: '3'

services:
  backendJava:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      app_net:
        ipv4_address: 172.20.0.2

  backendNode:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      app_net:
        ipv4_address: 172.20.0.4

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 172.20.0.3
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
