version: '3'

services:
  backend-java:
    image: jgmatosmota/backend-java:1.4
    command: ["java", "-jar", "/app/backend-java.jar"]
    ports:
      - "8080:8080"
    networks:
      app_net:
        ipv4_address: 172.20.0.2

  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      app_net:
        ipv4_address: 172.20.0.4
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      app_net:
        ipv4_address: 172.20.0.5

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
