version: '3'

services:
  backendJava:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backendNode:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
